CREATE DATABASE Users
GO

USE Users
GO

CREATE TABLE dbo.[User] (
	ID INT IDENTITY (1,1) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	IsAdmin BIT NULL,
	CONSTRAINT PK_UserID PRIMARY KEY (ID)
)