CREATE DATABASE EVENTO_ESCOLAR
GO

USE EVENTO_ESCOLAR
GO

CREATE TABLE EVENTO
(
COD_EVENTO INT NOT NULL IDENTITY (1,1),
DURACAO TIME NOT NULL,
TITULO VARCHAR(45) NOT NULL,
DESCRICAO VARCHAR(500),
DATA DATE NOT NULL,
HORARIO TIME NOT NULL,
SALA VARCHAR(MAX) NOT NULL,
IMAGEM_URL VARCHAR(MAX),
CONSTRAINT PK_EVENTO PRIMARY KEY (COD_EVENTO)
)
GO

CREATE TABLE PERFIL
(
COD_PERFIL INT NOT NULL IDENTITY (1,1),
DESCRICAO VARCHAR(45) NOT NULL,
CONSTRAINT PK_PERFIL PRIMARY KEY (COD_PERFIL)
)
GO

CREATE TABLE USUARIO
(
COD_USUARIO INT NOT NULL IDENTITY (1,1),
NOME VARCHAR(80) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
SENHA VARCHAR(MAX) NOT NULL,
CELULAR CHAR(11) NOT NULL,
COD_PERFIL INT,
CONSTRAINT PK_USUARIO PRIMARY KEY (COD_USUARIO),
CONSTRAINT FK_PERFIL_U FOREIGN KEY (COD_PERFIL) REFERENCES PERFIL (COD_PERFIL)
)
GO

CREATE TABLE INSCRICAO
(
COD_INSCRICAO INT NOT NULL IDENTITY (1,1),
COD_USUARIO INT,
COD_EVENTO INT,
DATA_HORA_INSC DATETIME NOT NULL,
DATA_HORA_PARTICIPACAO DATETIME NOT NULL,
CONSTRAINT PK_INSCRICAO PRIMARY KEY (COD_INSCRICAO),
CONSTRAINT FK_USUARIO_INSC FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO),
CONSTRAINT FK_EVENTO_INSC FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO (COD_EVENTO)
)
GO

CREATE TABLE FEEDBACK
(
COD_FEEDBACK INT NOT NULL IDENTITY (1,1),
COMENTARIO VARCHAR(500),
NOTA CHAR(5),
COD_INSCRICAO INT,
COD_EVENTO INT,
CONSTRAINT PK_FEEDBACK PRIMARY KEY (COD_FEEDBACK),
CONSTRAINT FK_INSCRICAO_FEED FOREIGN KEY (COD_INSCRICAO) REFERENCES INSCRICAO (COD_INSCRICAO),
CONSTRAINT FK_EVENTO_FEED FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO (COD_EVENTO)
)
GO

CREATE TABLE USUARIO_GERENCIA_EVENTO
(
COD_GERENCIA INT NOT NULL IDENTITY (1,1),
COD_USUARIO INT,
COD_EVENTO INT,
CONSTRAINT PK_GERENCIA PRIMARY KEY (COD_GERENCIA),
CONSTRAINT FK_USUARIO_GEREN FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO),
CONSTRAINT FK_GEREN_EVENTO FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO (COD_EVENTO)
)