//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserID { get; set; }

        [Required(ErrorMessage = "Por favor, preencha este campo.")]
        public string LoginEmail { get; set; }

        [Required(ErrorMessage = "Por favor, preencha este campo.")]
        public string PasswordHash { get; set; }

        public string LoginName { get; set; }
    }
}
